import { Job, Tool, UserRole, User } from '../types';

export const MOCK_JOBS: Job[] = [
  { 
    id: '1', 
    title: 'Corn Harvest Assistance Needed', 
    description: 'Looking for reliable hands to help with the seasonal corn harvest. Machinery experience is a plus.', 
    budget: 150, 
    location: 'Iowa City, Iowa', 
    postedBy: { id: 'u1', name: 'John Williams', role: UserRole.INNOVATOR, avatar: 'https://ui-avatars.com/api/?name=John+Williams&background=random', location: 'Iowa', bio: '', skills: [], rating: 4.8 }, 
    status: 'OPEN', 
    createdAt: '2023-09-15', 
    tags: ['Harvesting', 'Equipment Maintenance'],
    latitude: 41.6611,
    longitude: -91.5302,
    job_type: 'harvesting',
    pay_rate: 150,
    pay_type: 'day',
    duration_days: 5,
    workers_count_needed: 3,
    start_date: '2023-09-15',
    required_skills: ['Harvesting', 'Tractor']
  },
  { 
    id: '2', 
    title: 'Irrigation System Setup', 
    description: 'Need help setting up a new drip irrigation system for the vegetable patch.', 
    budget: 25, 
    location: 'Cedar Rapids, Iowa', 
    postedBy: { id: 'u1', name: 'John Williams', role: UserRole.INNOVATOR, avatar: 'https://ui-avatars.com/api/?name=John+Williams&background=random', location: 'Iowa', bio: '', skills: [], rating: 4.8 }, 
    status: 'OPEN', 
    createdAt: '2023-08-20', 
    tags: ['Irrigation', 'Equipment Maintenance'],
    latitude: 41.9779,
    longitude: -91.6656,
    job_type: 'irrigation',
    pay_rate: 25,
    pay_type: 'hour',
    duration_days: 2,
    workers_count_needed: 1,
    start_date: '2023-08-20'
  },
  { 
    id: '3', 
    title: 'Land Clearing Project', 
    description: 'Clearing 5 acres of brush for new planting season. Heavy lifting required.', 
    budget: 200, 
    location: 'Des Moines, Iowa', 
    postedBy: { id: 'u1', name: 'John Williams', role: UserRole.INNOVATOR, avatar: 'https://ui-avatars.com/api/?name=John+Williams&background=random', location: 'Iowa', bio: '', skills: [], rating: 4.8 }, 
    status: 'OPEN', 
    createdAt: '2023-08-25', 
    tags: ['Land Clearing', 'Tractor Operation'],
    latitude: 41.5868,
    longitude: -93.6250,
    job_type: 'clearing',
    pay_rate: 200,
    pay_type: 'day',
    duration_days: 3,
    workers_count_needed: 4,
    start_date: '2023-08-25'
  },
  { 
    id: '4', 
    title: 'Livestock Feeding Assistant', 
    description: 'Daily feeding and care for cattle herd. Morning shifts available.', 
    budget: 18, 
    location: 'Ames, Iowa', 
    postedBy: { id: 'u1', name: 'John Williams', role: UserRole.INNOVATOR, avatar: 'https://ui-avatars.com/api/?name=John+Williams&background=random', location: 'Iowa', bio: '', skills: [], rating: 4.8 }, 
    status: 'OPEN', 
    createdAt: '2023-09-01', 
    tags: ['Livestock', 'Feeding'],
    latitude: 42.0308,
    longitude: -93.6319,
    job_type: 'livestock',
    pay_rate: 18,
    pay_type: 'hour',
    duration_days: 14,
    workers_count_needed: 1,
    start_date: '2023-09-02'
  },
  { 
    id: '5', 
    title: 'Soybean Planting Crew', 
    description: 'Experienced planters needed for 200 acre soybean field.', 
    budget: 160, 
    location: 'Waterloo, Iowa', 
    postedBy: { id: 'u1', name: 'John Williams', role: UserRole.INNOVATOR, avatar: 'https://ui-avatars.com/api/?name=John+Williams&background=random', location: 'Iowa', bio: '', skills: [], rating: 4.8 }, 
    status: 'OPEN', 
    createdAt: '2023-09-10', 
    tags: ['Planting', 'Machinery'],
    latitude: 42.4922,
    longitude: -92.3401,
    job_type: 'planting',
    pay_rate: 160,
    pay_type: 'day',
    duration_days: 4,
    workers_count_needed: 5,
    start_date: '2023-09-12'
  },
  { 
    id: '6', 
    title: 'Barn Roof Repair', 
    description: 'Need help repairing storm damage on the main barn roof.', 
    budget: 30, 
    location: 'Dubuque, Iowa', 
    postedBy: { id: 'u1', name: 'John Williams', role: UserRole.INNOVATOR, avatar: 'https://ui-avatars.com/api/?name=John+Williams&background=random', location: 'Iowa', bio: '', skills: [], rating: 4.8 }, 
    status: 'OPEN', 
    createdAt: '2023-08-15', 
    tags: ['Construction', 'Repair'],
    latitude: 42.5006,
    longitude: -90.6648,
    job_type: 'other',
    pay_rate: 30,
    pay_type: 'hour',
    duration_days: 3,
    workers_count_needed: 2,
    start_date: '2023-08-18'
  },
  { 
    id: '7', 
    title: 'Grain Transport Driver', 
    description: 'CDL driver needed to transport grain to the silo.', 
    budget: 220, 
    location: 'Davenport, Iowa', 
    postedBy: { id: 'u1', name: 'John Williams', role: UserRole.INNOVATOR, avatar: 'https://ui-avatars.com/api/?name=John+Williams&background=random', location: 'Iowa', bio: '', skills: [], rating: 4.8 }, 
    status: 'OPEN', 
    createdAt: '2023-09-05', 
    tags: ['Transport', 'Driving'],
    latitude: 41.5236,
    longitude: -90.5776,
    job_type: 'transport',
    pay_rate: 220,
    pay_type: 'day',
    duration_days: 10,
    workers_count_needed: 2,
    start_date: '2023-09-06'
  },
  { 
    id: '8', 
    title: 'Orchard Maintenance', 
    description: 'Pruning and general maintenance for apple orchard.', 
    budget: 140, 
    location: 'Sioux City, Iowa', 
    postedBy: { id: 'u1', name: 'John Williams', role: UserRole.INNOVATOR, avatar: 'https://ui-avatars.com/api/?name=John+Williams&background=random', location: 'Iowa', bio: '', skills: [], rating: 4.8 }, 
    status: 'OPEN', 
    createdAt: '2023-08-30', 
    tags: ['Maintenance', 'Pruning'],
    latitude: 42.4999,
    longitude: -96.4003,
    job_type: 'harvesting',
    pay_rate: 140,
    pay_type: 'day',
    duration_days: 7,
    workers_count_needed: 4,
    start_date: '2023-09-01'
  }
];

export const MOCK_TOOLS: Tool[] = [
  { 
    id: '1', 
    name: 'Network Setup Kit', 
    description: 'Complete kit for farm connectivity.', 
    pricePerDay: 15, 
    owner: { id: 'u3', name: 'Mike Tools', role: UserRole.WORKER, avatar: 'https://picsum.photos/100/100?random=3', location: 'Accra', bio: '', skills: [], rating: 4.5 }, 
    image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?auto=format&fit=crop&q=80&w=400', 
    available: true, 
    category: 'Technology',
    latitude: 41.6500,
    longitude: -91.5500,
    rating: 4.5,
    total_reviews: 12
  },
  { 
    id: '2', 
    name: 'Corn Field Drone', 
    description: 'DJI Mavic 3 for aerial surveys.', 
    pricePerDay: 50, 
    owner: { id: 'u1', name: 'John Doe', role: UserRole.INNOVATOR, avatar: 'https://picsum.photos/100/100?random=1', location: 'Lagos', bio: '', skills: [], rating: 4.8 }, 
    image: 'https://images.unsplash.com/photo-1625246333195-58f216f73327?auto=format&fit=crop&q=80&w=400', 
    available: true, 
    category: 'Photography',
    latitude: 41.9800,
    longitude: -91.6700,
    rating: 4.8,
    total_reviews: 8
  },
  { 
    id: '3', 
    name: 'John Deere Tractor', 
    description: 'Heavy duty tractor for plowing.', 
    pricePerDay: 150, 
    owner: { id: 'u2', name: 'Jane Farm', role: UserRole.INVESTOR, avatar: 'https://picsum.photos/100/100?random=4', location: 'Nairobi', bio: '', skills: [], rating: 5.0 }, 
    image: 'https://images.unsplash.com/photo-1592982537447-6f2a6a0c7c18?auto=format&fit=crop&q=80&w=400', 
    available: true, 
    category: 'Heavy Machinery',
    latitude: 41.5900,
    longitude: -93.6300,
    rating: 5.0,
    total_reviews: 5
  },
];

export const MOCK_REVIEWS = [
  { id: 'r1', reviewer_id: 'u2', reviewer_name: 'Jane Smith', reviewer_photo: 'https://picsum.photos/100/100?random=2', reviewed_user_id: 'u3', tool_id: '1', rating: 5, comment: 'Great tool, worked perfectly!', created_date: '2023-10-15', review_type: 'tool' },
  { id: 'r2', reviewer_id: 'u1', reviewer_name: 'John Williams', reviewer_photo: 'https://ui-avatars.com/api/?name=John+Williams&background=random', reviewed_user_id: 'u3', tool_id: '1', rating: 4, comment: 'Good condition but battery drained fast.', created_date: '2023-11-01', review_type: 'tool' }
];

export const MOCK_WORKERS = [
  {
    id: '1',
    name: 'Maria Santos',
    role: 'Agricultural Specialist',
    rating: 4.9,
    location: 'Cedar Rapids, IA',
    hourlyRate: 18,
    jobsCompleted: 45,
    skills: ['Harvesting', 'Planting', 'Tractor Operation'],
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    verified: true,
    available: true,
    latitude: 41.9700,
    longitude: -91.6600
  },
  {
    id: '2',
    name: 'Maria Garcia',
    role: 'Livestock Manager',
    rating: 4.9,
    location: 'Fresno, CA',
    hourlyRate: 22,
    jobsCompleted: 32,
    skills: ['Livestock Care', 'Organic Farming', 'Crop Spraying'],
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=150',
    verified: true,
    available: true,
    latitude: 36.7378,
    longitude: -119.7871
  },
  {
    id: '3',
    name: 'John Martinez',
    role: 'Farm Hand',
    rating: 4.8,
    location: 'Sacramento, CA',
    hourlyRate: 18,
    jobsCompleted: 45,
    skills: ['Harvesting', 'Tractor Operation', 'Planting'],
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    verified: true,
    available: true,
    latitude: 38.5816,
    longitude: -121.4944
  }
];

export const MOCK_WALLET_DATA = [
  { name: 'Mon', amount: 400 },
  { name: 'Tue', amount: 300 },
  { name: 'Wed', amount: 600 },
  { name: 'Thu', amount: 800 },
  { name: 'Fri', amount: 500 },
  { name: 'Sat', amount: 900 },
  { name: 'Sun', amount: 1000 },
];

export const MOCK_USERS: User[] = [
  { 
    id: 'u1', 
    full_name: 'John Williams', 
    user_email: 'john@example.com', 
    user_type: 'INNOVATOR', 
    photo_url: 'https://ui-avatars.com/api/?name=John+Williams&background=random', 
    account_status: 'approved', 
    created_date: '2023-01-15', 
    wallet_balance: 1250,
    location_name: 'Iowa City, IA',
    availability: 'available',
    rating: 4.8,
    name: 'John Williams',
    role: UserRole.INNOVATOR,
    avatar: 'https://ui-avatars.com/api/?name=John+Williams&background=random',
    location: 'Iowa'
  },
  { 
    id: 'u2', 
    full_name: 'Jane Smith', 
    user_email: 'jane@example.com', 
    user_type: 'INVESTOR', 
    photo_url: 'https://picsum.photos/100/100?random=2', 
    account_status: 'approved', 
    created_date: '2023-02-20', 
    wallet_balance: 5000,
    location_name: 'Nairobi, Kenya',
    availability: 'busy',
    rating: 5.0,
    name: 'Jane Smith',
    role: UserRole.INVESTOR,
    avatar: 'https://picsum.photos/100/100?random=2',
    location: 'Nairobi'
  },
  { 
    id: 'u3', 
    full_name: 'Mike Tools', 
    user_email: 'mike@example.com', 
    user_type: 'WORKER', 
    photo_url: 'https://picsum.photos/100/100?random=3', 
    account_status: 'pending', 
    created_date: '2023-11-10', 
    wallet_balance: 120,
    location_name: 'Accra, Ghana',
    availability: 'available',
    rating: 4.5,
    name: 'Mike Tools',
    role: UserRole.WORKER,
    avatar: 'https://picsum.photos/100/100?random=3',
    location: 'Accra'
  },
];

export const MOCK_BOOKINGS = [
  { id: 'b1', tool_id: '1', tool_name: 'Heavy Duty Drill', tool_image: 'https://picsum.photos/400/300?random=1', renter_id: 'u1', renter_name: 'John Doe', owner_id: 'u3', owner_name: 'Mike Tools', start_date: '2023-11-01', end_date: '2023-11-03', status: 'pending', total_amount: 45 },
  { id: 'b2', tool_id: '2', tool_name: 'Drone Camera', tool_image: 'https://picsum.photos/400/300?random=2', renter_id: 'u3', renter_name: 'Mike Tools', owner_id: 'u1', owner_name: 'John Doe', start_date: '2023-10-25', end_date: '2023-10-26', status: 'completed', total_amount: 50 },
];